// Objective-C API for talking to daidai-panel/mobile Go package.
//   gobind -lang=objc daidai-panel/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileMobileServer;
@class MobilePanelManager;
@class MobileSyncData;
@class MobileSyncDataItems;
@class MobileSyncManager;
@class MobileSyncStatus;

/**
 * MobileServer is the main entry point for mobile platforms.
 */
@interface MobileMobileServer : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

/**
 * PanelManager is the gomobile-compatible interface for mobile platforms.
 */
@interface MobilePanelManager : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Cleanup releases resources.
 */
- (void)cleanup;
/**
 * ExportData exports the database data as JSON string.
 */
- (NSString* _Nonnull)exportData:(NSError* _Nullable* _Nullable)error;
/**
 * GetPort returns the server port.
 */
- (long)getPort;
/**
 * GetServerURL returns the server URL.
 */
- (NSString* _Nonnull)getServerURL;
/**
 * GetStatus returns a JSON string with server status.
 */
- (NSString* _Nonnull)getStatus;
/**
 * GetUptime returns the server uptime in seconds.
 */
- (int64_t)getUptime;
/**
 * ImportData imports data from a JSON string.
 */
- (BOOL)importData:(NSString* _Nullable)jsonData error:(NSError* _Nullable* _Nullable)error;
/**
 * Initialize sets up the mobile environment.
dataDir: path to app data directory (e.g., /data/data/com.daidai.panel/files)
webDir: path to web assets (e.g., assets/web)
 */
- (BOOL)initialize:(NSString* _Nullable)dataDir webDir:(NSString* _Nullable)webDir error:(NSError* _Nullable* _Nullable)error;
/**
 * IsAutoStart returns whether auto-start is enabled.
 */
- (BOOL)isAutoStart;
/**
 * IsRunning returns whether the server is currently running.
 */
- (BOOL)isRunning;
/**
 * SetAutoStart configures whether the server should start automatically.
 */
- (void)setAutoStart:(BOOL)enabled;
/**
 * SetPort sets the server port (must be called before StartServer).
 */
- (void)setPort:(long)port;
/**
 * StartServer starts the panel HTTP server.
 */
- (BOOL)startServer:(NSError* _Nullable* _Nullable)error;
/**
 * StopServer stops the panel HTTP server.
 */
- (BOOL)stopServer:(NSError* _Nullable* _Nullable)error;
/**
 * SyncData syncs data with remote server.
 */
- (BOOL)syncData:(NSString* _Nullable)serverURL apiKey:(NSString* _Nullable)apiKey error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * SyncData represents the data structure for synchronization
 */
@interface MobileSyncData : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull version;
@property (nonatomic) int64_t timestamp;
@property (nonatomic) NSString* _Nonnull deviceID;
@property (nonatomic) NSString* _Nonnull platform;
// skipped field SyncData.Data with unsupported type: daidai-panel/mobile.SyncDataItems

@end

/**
 * SyncDataItems contains all syncable data
 */
@interface MobileSyncDataItems : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field SyncDataItems.Tasks with unsupported type: []encoding/json.RawMessage

// skipped field SyncDataItems.EnvVars with unsupported type: []encoding/json.RawMessage

// skipped field SyncDataItems.Subscriptions with unsupported type: []encoding/json.RawMessage

// skipped field SyncDataItems.NotifyChannels with unsupported type: []encoding/json.RawMessage

// skipped field SyncDataItems.TaskViews with unsupported type: []encoding/json.RawMessage

@end

/**
 * SyncManager handles data synchronization
 */
@interface MobileSyncManager : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewSyncManager creates a new SyncManager instance
 */
- (nullable instancetype)init:(NSString* _Nullable)dataDir;
/**
 * ExportData exports all syncable data from the database
 */
- (MobileSyncData* _Nullable)exportData:(NSError* _Nullable* _Nullable)error;
/**
 * ExportToFile exports sync data to a file
 */
- (BOOL)exportToFile:(NSString* _Nullable)filePath error:(NSError* _Nullable* _Nullable)error;
/**
 * ExportToJSON exports sync data as JSON string
 */
- (NSString* _Nonnull)exportToJSON:(NSError* _Nullable* _Nullable)error;
/**
 * GetSyncStatus returns the current sync status
 */
- (MobileSyncStatus* _Nullable)getSyncStatus:(NSError* _Nullable* _Nullable)error;
/**
 * ImportData imports syncable data into the database
 */
- (BOOL)importData:(MobileSyncData* _Nullable)syncData error:(NSError* _Nullable* _Nullable)error;
/**
 * ImportFromFile imports sync data from a file
 */
- (BOOL)importFromFile:(NSString* _Nullable)filePath error:(NSError* _Nullable* _Nullable)error;
/**
 * ImportFromJSON imports sync data from JSON string
 */
- (BOOL)importFromJSON:(NSString* _Nullable)jsonStr error:(NSError* _Nullable* _Nullable)error;
/**
 * SaveSyncStatus saves the sync status
 */
- (BOOL)saveSyncStatus:(MobileSyncStatus* _Nullable)status error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * SyncStatus represents the current sync status
 */
@interface MobileSyncStatus : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t lastSyncTime;
@property (nonatomic) NSString* _Nonnull lastSyncDevice;
@property (nonatomic) BOOL hasConflict;
@property (nonatomic) long conflictCount;
@end

/**
 * GetInstance returns the singleton PanelManager instance.
 */
FOUNDATION_EXPORT MobilePanelManager* _Nullable MobileGetInstance(void);

/**
 * NewSyncManager creates a new SyncManager instance
 */
FOUNDATION_EXPORT MobileSyncManager* _Nullable MobileNewSyncManager(NSString* _Nullable dataDir);

#endif
